"""baseline current schema

Revision ID: 0001_baseline
Revises:
Create Date: 2026-08-01 01:33:51.117569
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_EXPECTED_COLUMNS = {
    "bangumi": {
        "id", "title", "summary", "cover_url", "banner_url", "type", "lang",
        "year", "status", "tags", "genres", "rating", "rating_count",
        "bangumi_id", "created_at", "updated_at",
    },
    "bangumi_collections": {"id", "user_id", "bangumi_id", "type", "created_at"},
    "bangumi_episodes": {
        "id", "bangumi_id", "number", "title", "vod_url", "duration", "created_at",
    },
    "catalog_subjects": {
        "id", "stable_id", "provider", "provider_id", "media_type", "title",
        "original_title", "aliases_json", "metadata_json", "popularity", "updated_at",
    },
    "characters": {
        "id", "bangumi_id", "name", "role", "avatar_url", "summary", "seiyuu",
    },
    "comment_likes": {"id", "user_id", "comment_id", "created_at"},
    "comments": {
        "id", "type", "target_id", "user_id", "parent_id", "reply_to", "contents",
        "like_count", "created_at",
    },
    "danmaku": {
        "id", "bangumi_id", "episode_id", "user_id", "type", "time", "text",
        "color", "date", "danmaku_id",
    },
    "persons": {"id", "bangumi_id", "name", "role", "avatar_url", "summary"},
    "play_history": {
        "id", "user_id", "bangumi_id", "episode_id", "position", "created_at",
        "updated_at",
    },
    "playback_cache": {
        "id", "subject_id", "episode", "title", "lines_json", "line_count",
        "verified_at", "created_at",
    },
    "source_bindings": {
        "id", "stable_id", "source_id", "source_name", "matched_title", "media_type",
        "year", "score", "episode_count", "enabled", "success_count", "failure_count",
        "last_success_at", "last_failure_at", "updated_at",
    },
    "source_health": {
        "id", "source_name", "success_count", "failure_count", "consecutive_failures",
        "last_status", "last_checked_at", "latency_ms",
    },
    "thread_collections": {"id", "user_id", "thread_id", "created_at"},
    "thread_images": {
        "id", "thread_id", "color", "width", "height", "original", "master",
        "original_size", "master_size",
    },
    "thread_likes": {"id", "user_id", "thread_id", "created_at"},
    "threads": {
        "id", "title", "body", "tags", "nsfw", "ai", "user_id", "like_count",
        "collect_count", "comment_count", "created_at", "updated_at",
    },
    "user_tokens": {"id", "user_id", "token", "created_at"},
    "users": {
        "id", "email", "name", "password_hash", "role", "sex", "avatar", "exp",
        "coin", "color", "address", "created_at", "updated_at",
    },
    "verify_codes": {"id", "email", "code", "created_at", "expires_at"},
}


def _adopt_existing_current_schema() -> bool:
    """Adopt only a complete pre-Alembic schema without mutating its data."""
    inspector = sa.inspect(op.get_bind())
    existing_tables = set(inspector.get_table_names()) - {"alembic_version"}
    if not existing_tables:
        return False
    missing_tables = set(_EXPECTED_COLUMNS) - existing_tables
    missing_columns = {
        table: sorted(
            columns
            - {column["name"] for column in inspector.get_columns(table)}
        )
        for table, columns in _EXPECTED_COLUMNS.items()
        if table in existing_tables
        and columns
        - {column["name"] for column in inspector.get_columns(table)}
    }
    if missing_tables or missing_columns:
        raise RuntimeError(
            "Existing database does not match the Zeluna baseline; "
            f"missing tables={sorted(missing_tables)}, "
            f"missing columns={missing_columns}"
        )
    return True


def upgrade() -> None:
    if _adopt_existing_current_schema():
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bangumi',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('cover_url', sa.String(length=1000), nullable=False),
    sa.Column('banner_url', sa.String(length=1000), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('lang', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.Column('genres', sa.Text(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('bangumi_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stable_id', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_id', sa.String(length=100), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('original_title', sa.String(length=500), nullable=False),
    sa.Column('aliases_json', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('popularity', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalog_subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_subjects_media_type'), ['media_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_subjects_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_subjects_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_subjects_stable_id'), ['stable_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_catalog_subjects_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_subjects_updated_at'), ['updated_at'], unique=False)

    op.create_table('playback_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.String(length=200), nullable=False),
    sa.Column('episode', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('lines_json', sa.Text(), nullable=False),
    sa.Column('line_count', sa.Integer(), nullable=False),
    sa.Column('verified_at', sa.Float(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('playback_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playback_cache_subject_id'), ['subject_id'], unique=False)

    op.create_table('source_bindings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stable_id', sa.String(length=200), nullable=False),
    sa.Column('source_id', sa.String(length=300), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('matched_title', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('episode_count', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('last_success_at', sa.Float(), nullable=False),
    sa.Column('last_failure_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stable_id', 'source_id', name='uq_source_binding')
    )
    with op.batch_alter_table('source_bindings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_bindings_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_bindings_source_name'), ['source_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_bindings_stable_id'), ['stable_id'], unique=False)

    op.create_table('source_health',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_status', sa.String(length=30), nullable=False),
    sa.Column('last_checked_at', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_health', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_health_source_name'), ['source_name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('avatar', sa.String(length=500), nullable=False),
    sa.Column('exp', sa.Integer(), nullable=False),
    sa.Column('coin', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=True)

    op.create_table('verify_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bangumi_collections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bangumi_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['bangumi_id'], ['bangumi.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bangumi_episodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bangumi_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('vod_url', sa.Text(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['bangumi_id'], ['bangumi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bangumi_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.String(length=1000), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('seiyuu', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['bangumi_id'], ['bangumi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.String(length=100), nullable=False),
    sa.Column('reply_to', sa.String(length=200), nullable=False),
    sa.Column('contents', sa.Text(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bangumi_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.String(length=1000), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['bangumi_id'], ['bangumi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.Column('nsfw', sa.Boolean(), nullable=False),
    sa.Column('ai', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('collect_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_tokens_token'), ['token'], unique=True)

    op.create_table('comment_likes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('danmaku',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bangumi_id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('time', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Float(), nullable=False),
    sa.Column('danmaku_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['bangumi_id'], ['bangumi.id'], ),
    sa.ForeignKeyConstraint(['episode_id'], ['bangumi_episodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('play_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bangumi_id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['bangumi_id'], ['bangumi.id'], ),
    sa.ForeignKeyConstraint(['episode_id'], ['bangumi_episodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thread_collections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thread_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('original', sa.String(length=1000), nullable=False),
    sa.Column('master', sa.String(length=1000), nullable=False),
    sa.Column('original_size', sa.Integer(), nullable=False),
    sa.Column('master_size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thread_likes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thread_likes')
    op.drop_table('thread_images')
    op.drop_table('thread_collections')
    op.drop_table('play_history')
    op.drop_table('danmaku')
    op.drop_table('comment_likes')
    with op.batch_alter_table('user_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_tokens_token'))

    op.drop_table('user_tokens')
    op.drop_table('threads')
    op.drop_table('persons')
    op.drop_table('comments')
    op.drop_table('characters')
    op.drop_table('bangumi_episodes')
    op.drop_table('bangumi_collections')
    op.drop_table('verify_codes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_name'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('source_health', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_health_source_name'))

    op.drop_table('source_health')
    with op.batch_alter_table('source_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_bindings_stable_id'))
        batch_op.drop_index(batch_op.f('ix_source_bindings_source_name'))
        batch_op.drop_index(batch_op.f('ix_source_bindings_source_id'))

    op.drop_table('source_bindings')
    with op.batch_alter_table('playback_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playback_cache_subject_id'))

    op.drop_table('playback_cache')
    with op.batch_alter_table('catalog_subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalog_subjects_updated_at'))
        batch_op.drop_index(batch_op.f('ix_catalog_subjects_title'))
        batch_op.drop_index(batch_op.f('ix_catalog_subjects_stable_id'))
        batch_op.drop_index(batch_op.f('ix_catalog_subjects_provider_id'))
        batch_op.drop_index(batch_op.f('ix_catalog_subjects_provider'))
        batch_op.drop_index(batch_op.f('ix_catalog_subjects_media_type'))

    op.drop_table('catalog_subjects')
    op.drop_table('bangumi')
    # ### end Alembic commands ###
